export const TASK_PENDING = "TASK_PENDING";
export const TASK_REJECT = "TASK_REJECT";

export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";

export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS";

export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
